name: BuildSageMakerModel
on:
  push:
    branches:
      - master
env:
  AWS_REGION: us-east-1
  SAGEMAKER_PROJECT_NAME: mlops-abalone-v2

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade . botocore boto3 awscli

      - name: Configure AWS Credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build SageMaker Pipeline
        run: |
          PROJECT=$(aws sagemaker describe-project --project-name ${{ env.SAGEMAKER_PROJECT_NAME }} --query ProjectId --output text)
          PROJECT_ARN=$(aws sagemaker describe-project --project-name ${{ env.SAGEMAKER_PROJECT_NAME }} --query ProjectArn --output text)

          export SAGEMAKER_PROJECT_ARN=$PROJECT_ARN
          export SAGEMAKER_PROJECT_ID=$PROJECT
          export SAGEMAKER_PROJECT_NAME_ID="${{ env.SAGEMAKER_PROJECT_NAME }}-$PROJECT"
          export ARTIFACT_BUCKET="sagemaker-us-east-1-769265885190"
          export SAGEMAKER_PIPELINE_ROLE_ARN="arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):role/service-role/AmazonSageMakerServiceCatalogProductsUseRole"

          run-pipeline \
            --module-name pipelines.abalone.pipeline \
            --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN \
            --tags "[{\"Key\":\"sagemaker:project-name\",\"Value\":\"${{ env.SAGEMAKER_PROJECT_NAME }}\"},{\"Key\":\"sagemaker:project-id\",\"Value\":\"$PROJECT\"}]" \
            --kwargs "{\"region\":\"${{ env.AWS_REGION }}\",\"sagemaker_project_arn\":\"$SAGEMAKER_PROJECT_ARN\",\"role\":\"$SAGEMAKER_PIPELINE_ROLE_ARN\",\"default_bucket\":\"$ARTIFACT_BUCKET\",\"pipeline_name\":\"$SAGEMAKER_PROJECT_NAME_ID\",\"model_package_group_name\":\"$SAGEMAKER_PROJECT_NAME_ID\",\"base_job_prefix\":\"$SAGEMAKER_PROJECT_NAME_ID\"}"